SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio AS EUR, ROUND(precio * 0.9) AS USD FROM producto;
SELECT nombre AS nom de producto, precio AS euros, round(precio * 0.9) AS dòlars FROM producto;
SELECT UPPER(nombre) AS nombre , precio FROM producto;
SELECT LOWER(nombre) AS nombre , precio FROM producto;
SELECT nombre, SUBSTRING(nombre,1,2) AS dos FROM fabricante;
SELECT nombre , ROUND(precio) AS precio FROM producto;
SELECT nombre , ROUND(precio) AS precio FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT DISTINCT codigo_fabricante FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, ROUND(precio) AS precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 0, 5;
SELECT * FROM fabricante LIMIT 3, 2;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 0, 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 0, 1;
SELECT nombre FROM fabricante WHERE codigo=2;
SELECT p.nombre AS nombre, precio AS precio, f.nombre AS fabricante FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante;
SELECT p.nombre AS nombre, precio AS precio, f.nombre AS fabricante FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante ORDER BY fabricante ASC;
SELECT p.codigo, p.nombre AS producto, f.codigo, f.nombre AS fabricante FROM producto p INNER JOIN fabricante f ON f.codigo=p.codigo_fabricante;
SELECT p.nombre AS nombre, precio AS precio, f.nombre AS fabricante FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante ORDER BY precio ASC LIMIT 0, 1;
SELECT p.nombre AS nombre, precio AS precio, f.nombre AS fabricante FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante ORDER BY precio DESC LIMIT 0, 1;
SELECT p.nombre AS nombre, f.nombre AS fabricante FROM producto p INNER JOIN fabricante f ON f codigo = p.codigo_fabricante WHERE f.nombre='Lenovo';
SELECT p.nombre AS nombre, precio AS precio, f.nombre AS fabricante FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre='Crucial' AND precio > 200;
SELECT p.nombre AS nombre, f.nombre AS fabricante FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre='Asus' OR f.nombre='Hewlett-Packard' OR f.nombre='Seagate';
SELECT p.nombre AS nombre, f.nombre AS fabricante FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre IN ('Asus', 'Hewlett-Packard', 'Seagate');
SELECT p.nombre AS nombre, f.nombre AS fabricante FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre LIKE '%e';
SELECT p.nombre AS nombre, precio AS precio, f.nombre AS fabricante FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre LIKE '%w%';
SELECT p.nombre AS nombre, precio AS precio, f.nombre AS fabricante FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE precio>=180 ORDER BY precio DESC, f.nombre ASC;
SELECT p.nombre AS nombre, codigo AS codigo FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE precio>=180 ORDER BY precio DESC, f.nombre ASC;
SELECT f.codigo, f.nombre AS fabricante, p.nombre AS producto FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT f.codigo, f.nombre AS fabricante, p.nombre AS producto FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante WHERE p.nombre = NULL;
SELECT f.nombre AS fabricante, p.nombre AS producto FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante WHERE f.nombre ='Lenovo';
SELECT p.nombre, precio, p.codigo, f.nombre AS fabricante FROM producto p JOIN fabricante f WHERE f.codigo = p.codigo_fabricante AND precio = (SELECT precio FROM producto p, fabricante f WHERE f.codigo = p.codigo_fabricante AND f.nombre='Lenovo' ORDER BY precio DESC LIMIT 0, 1);
SELECT precio FROM producto p, fabricante f WHERE f.codigo = p.codigo_fabricante AND f.nombre='Lenovo'ORDER BY precio DESC LIMIT 0, 1;
SELECT precio FROM producto p, fabricante f WHERE f.codigo = p.codigo_fabricante AND f.nombre='Hewlett-Packard' ORDER BY precio ASC LIMIT 0, 1;
SELECT p.nombre AS producto, precio FROM producto p WHERE precio >= (SELECT precio FROM producto p, fabricante f WHERE f.codigo = p.codigo_fabricante AND f.nombre='Lenovo' ORDER BY precio DESC LIMIT 0, 1);
SELECT p.nombre AS producto, precio FROM producto p, fabricante f WHERE f.codigo = p.codigo_fabricante AND f.nombre='Asus' AND precio > (SELECT AVG(precio) FROM producto p WHERE f.codigo = p.codigo_fabricante);